### ISSUE TITLE
Add support for color values with leading sharp symbol

### ISSUE THREAD

**Issue by AlexanderVorobyov** [unity-game-framework-actions/labels-update#2]
Example:
```yaml
- name: Label text
  description: Description text.
  color: '#fef2c0'
```
